// Build the bundled English word list for local scoring (requirements §5.3.7).
// Source: hermitdave/FrequencyWords (MIT) — frequency-ranked lists derived from the
// OpenSubtitles corpus (OPUS; Lison & Tiedemann 2016). See NOTICE.md.
//
// The committed src/core/corpus-data.js is the source of truth (the extension never fetches
// at runtime); this script documents how to regenerate it reproducibly. It is PINNED to a
// specific upstream commit and verifies the download against a known SHA-256 so the result
// is deterministic and tamper-evident. Run: node tools/build-corpus.mjs
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const COMMIT = '525f9b560de45753a5ea01069454e72e9aa541c6'; // hermitdave/FrequencyWords, pinned
const SOURCE = `https://raw.githubusercontent.com/hermitdave/FrequencyWords/${COMMIT}/content/2018/en/en_50k.txt`;
const EXPECTED_SHA256 = '5351ff405b1126ef555791dd4d9798a48e3e9a501a9fc481a9da957752cfb458';
const LIMIT = Number(process.env.CORPUS_LIMIT || 20000);

// Drop subtitle-corpus noise: profanity/slurs (Web Store optics) and the most common
// non-English function words that leak in from multilingual subtitles (they would slightly
// inflate dictionary coverage on foreign text). Not exhaustive — just the high-frequency
// offenders that actually appear in the top 20k.
const DENYLIST = new Set([
  // profanity / slurs
  'fuck', 'fucking', 'fucked', 'shit', 'shitty', 'bitch', 'cunt', 'nigga', 'nigger',
  'pussy', 'cock', 'dick', 'asshole', 'whore', 'slut', 'motherfucker', 'bullshit',
  // common non-English (es/fr/de/it/pt) function-word leakage
  'que', 'los', 'las', 'para', 'por', 'con', 'una', 'como', 'pero', 'más', 'esta',
  'este', 'eso', 'qué', 'und', 'der', 'die', 'das', 'ist', 'nicht', 'ich', 'sie',
  'mit', 'auf', 'ein', 'eine', 'je', 'ne', 'pas', 'vous', 'est', 'une', 'pour', 'sur',
  'che', 'non', 'mi', 'ti', 'il', 'di', 'da', 'um', 'em', 'nao', 'voce',
]);

const res = await fetch(SOURCE);
if (!res.ok) throw new Error(`fetch failed: ${res.status} ${res.statusText}`);
const bytes = Buffer.from(await res.arrayBuffer());
const digest = createHash('sha256').update(bytes).digest('hex');
if (digest !== EXPECTED_SHA256) {
  throw new Error(`source integrity check failed:\n  expected ${EXPECTED_SHA256}\n  got      ${digest}`);
}

const words = [];
const seen = new Set();
for (const line of bytes.toString('utf8').split('\n')) {
  const w = line.split(/\s+/)[0]?.trim().toLowerCase();
  if (!w || seen.has(w) || DENYLIST.has(w)) continue;
  if (!/^[a-z]{2,15}$/.test(w)) continue; // alphabetic only, drop single letters / junk
  seen.add(w);
  words.push(w);
  if (words.length >= LIMIT) break;
}

const out = fileURLToPath(new URL('../src/core/corpus-data.js', import.meta.url));
const header =
  `// GENERATED by tools/build-corpus.mjs — do not edit by hand.\n` +
  `// Source: hermitdave/FrequencyWords @ ${COMMIT} (MIT), top ${words.length} alphabetic\n` +
  `// English words by frequency. Regenerate with: npm run build:corpus\n`;
writeFileSync(out, `${header}export const WORDS = '${words.join(' ')}'.split(' ');\n`);
console.log(`verified sha256 ${digest}; wrote ${words.length} words -> src/core/corpus-data.js`);
